### ISSUE TITLE
mismatched html tags

### ISSUE THREAD

**Issue by nathanallen** [ychoy/carpe-gov#11]
Error: End tag `div` seen, but there were open elements.
From line 74, column 13; to line 74, column 18
  `</div>`

Error: Unclosed element `fieldset`.
From line 34, column 11; to line 34, column 20
  `<fieldset>`

Error: Unclosed element `form`.
From line 33, column 9; to line 33, column 38
  `<form class="form-horizontal">`

Error: Stray end tag `fieldset`.
From line 85, column 11; to line 85, column 21
  `</fieldset>`

Error: Stray end tag `form`.
From line 86, column 9; to line 86, column 15
  `</form>`

Error: Stray end tag `div`.
From line 88, column 7; to line 88, column 12
  `</div>`

**Comment by ychoy** [comment]
HTML tags fixed
